USE AdventureWorksDW2022;

WITH VENDAS (ANO, MES, TOTAL_VENDIDO) AS (
	SELECT
		DATEPART(YEAR, OrderDate) AS ANO,
		DATEPART(MONTH, OrderDate) AS MES, 
		SUM(SalesAmount) AS TOTAL_VENDIDO
	FROM FactInternetSales
	GROUP BY DATEPART(YEAR, OrderDate), DATEPART(MONTH, OrderDate)
) 

SELECT 
	ANO,
	MES, 
	FORMAT(TOTAL_VENDIDO, 'N0') AS TOTAL_VENDIDO,
	FORMAT(LAG(TOTAL_VENDIDO, 1, '-') OVER (ORDER BY ANO, MES), 'N0') AS TOTAL_VENDIDO_MES_ANTERIOR,
	FORMAT(TOTAL_VENDIDO - LAG(TOTAL_VENDIDO, 1, '-') OVER (ORDER BY ANO, MES), 'N0') AS VALOR_DIFERENCA,
	FORMAT(
		(TOTAL_VENDIDO - LAG(TOTAL_VENDIDO) OVER (ORDER BY ANO, MES)) * 1.0 
		/ LAG(TOTAL_VENDIDO) OVER (ORDER BY ANO, MES),
		'P0'
	) AS VARIACAO_PERCENTUAL
FROM VENDAS
	
