USE AdventureWorksDW2022;

WITH VENDAS_PRODUTO (PRODUTO, TOTAL_CUSTO, TOTAL_VENDAS, QUANTIDADE) AS (
	SELECT 
		ProductKey AS PRODUTO,
		SUM(TotalProductCost) AS TOTAL_CUSTO,
		SUM(SalesAmount) AS TOTAL_VENDAS,
		SUM(OrderQuantity) AS QUANTIDADE
	FROM FactInternetSales
	GROUP BY ProductKey
)

SELECT 
	P.EnglishProductName AS NOME_PRODUTO,
	V.QUANTIDADE,
	FORMAT(V.TOTAL_CUSTO, 'N0') AS TOTAL_CUSTO,
	FORMAT(V.TOTAL_VENDAS, 'N0') AS TOTAL_VENDAS,
	FORMAT((V.TOTAL_VENDAS - V.TOTAL_CUSTO), 'N0') AS LUCRO,
	FORMAT(((V.TOTAL_VENDAS - V.TOTAL_CUSTO) / V.TOTAL_VENDAS) * 1.0, 'P0') AS MARGEM_LUCRO
FROM VENDAS_PRODUTO V
INNER JOIN DimProduct P ON P.ProductKey = V.PRODUTO
ORDER BY MARGEM_LUCRO DESC;
