USE AdventureWorksDW2022;

WITH VENDAS (ANO, MES, TOTAL_VENDAS) AS (
	SELECT
		DATEPART(YEAR, OrderDate) AS ANO,
		DATEPART(MONTH, OrderDate) AS MES,
		SUM(SalesAmount) AS TOTAL_VENDAS
	FROM FactInternetSales
	GROUP BY DATEPART(YEAR, OrderDate), DATEPART(MONTH, OrderDate)
)

SELECT 
	ANO,
	MES,
	FORMAT(TOTAL_VENDAS, 'N0') AS TOTAL_VENDAS,
	FORMAT(LAG(TOTAL_VENDAS, 1) OVER (PARTITION BY MES ORDER BY ANO), 'N0') AS VENDAS_ANO_ANTERIOR,
	FORMAT((TOTAL_VENDAS - LAG(TOTAL_VENDAS, 1) OVER (PARTITION BY MES ORDER BY ANO)), 'N0') AS DIFERENCA_ABSOLUTA,
	FORMAT(
		(TOTAL_VENDAS - LAG(TOTAL_VENDAS, 1) OVER (PARTITION BY MES ORDER BY ANO) * 1.0) / 
		 LAG(TOTAL_VENDAS, 1) OVER (PARTITION BY MES ORDER BY ANO),
		'P0'
	) AS VARIACAO_PERCENTUAL_YOY
FROM VENDAS
ORDER BY ANO, MES;
