USE AdventureWorksDW2022;

WITH VENDAS_PAIS (PAIS, QTDE_PEDIDOS, FATURAMENTO, FRETE_TOTAL, DIAS_PARA_ENVIAR) AS (
	SELECT
		G.EnglishCountryRegionName AS PAIS,
		SUM(S.OrderQuantity) AS QTDE_PEDIDOS,
		SUM(S.SalesAmount) AS FATURAMENTO,
		SUM(S.Freight)AS FRETE_TOTAL,
		DATEDIFF(DAY, OrderDate, ShipDate) AS DIAS_PARA_ENVIAR
	FROM FactInternetSales AS S
	INNER JOIN DimCustomer AS C ON C.CustomerKey = S.CustomerKey
	INNER JOIN DimGeography AS G ON G.GeographyKey = C.GeographyKey
	GROUP BY G.EnglishCountryRegionName, DATEDIFF(DAY, OrderDate, ShipDate)
)

SELECT 
	PAIS, 
	QTDE_PEDIDOS,
	FORMAT(FATURAMENTO, 'N0') AS FATURAMENTO,
	FORMAT(FRETE_TOTAL, 'N0') AS FRETE_TOTAL,
	FORMAT(FRETE_TOTAL / QTDE_PEDIDOS, 'N0') AS FRETE_MEDIO,
	FORMAT((FRETE_TOTAL / FATURAMENTO) * 1.0, 'P2') AS PORCENTAGEM_FRETE,
	DIAS_PARA_ENVIAR
FROM VENDAS_PAIS
ORDER BY FATURAMENTO DESC;


